---
title: "Main"
author: "Aleksander Petrovskii"
date: "July 2, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Моделирование основных решений
В данном документе будет производится макетирование основных решений дипломной работы. Рабочий вариант будет реализован в виде программы на Shiny R.


## Выбор и загрузка трафика

### Первое - структурируем "сырой" pcap и отфильтруем нужные поля

```{bash echo = TRUE}
#!/bin/sh
if [ $# -ne 2 ]
then
	echo "Let's try: pcap_to_txt.sh from_file.pcap to_file.txt "
else
tshark -r $1 -Tfields -E separator=, -E header=y -E quote=d -e frame.number -e frame.time -e frame.time_delta -e frame.len -e frame.protocols -e eth.dst -e eth.src -e eth.dst_resolved -e eth.src_resolved -e eth.type -e ip.version -e ip.len -e ip.id -e ip.flags -e ip.frag_offset -e ip.ttl -e ip.proto -e ip.src -e ip.dst -e tcp.srcport -e tcp.dstport -e tcp.stream -e tcp.len -e tcp.seq -e tcp.hdr_len -e tcp.flags.res -e tcp.flags.ns -e tcp.flags.cwr -e tcp.flags.ecn -e tcp.flags.urg -e tcp.flags.ack -e tcp.flags.push -e tcp.flags.reset -e tcp.flags.syn  -e _ws.expert.message -e _ws.expert.severity -e _ws.expert.group -e tcp.flags.fin > $2
fi

```

## Choose the file

```{r echo=TRUE}
#set path to file with traffic dump`s
knitr::opts_knit$set(root.dir = '/home/petr0vsk/WorkR/SnortR/2009_CDX_Datasets/')
all.files <- list.files('2009_CDX_Datasets')
#convert files from pcap to table
if ( length(all.files) > 0 ) {
  for(i in 1:length(all.files)){
    print(all.files[i])
    
  }
  
} else { # if ifles not exist`s find pcap manyaly
  print("Can`t find file for processing, please choose it manualy")
  file.choose(new = FALSE)
}
  

```



